### ISSUE TITLE
Deephunter 2.0 vs 1.0?

### ISSUE THREAD

**Issue by ackdav** [Shimmer93/Deephunter-backup#1]
I'm quite confused about where I can find the code of the paper.
I see in the README that the original implementation was on top of AFL, and then version 2.0 is with tensorflow. However, did you measure the performance difference? Can I still have access to the original code that produced the results in the paper?

**Comment by Shimmer93** [comment]
I'm not one of the authors of the paper.
I found the code of the paper (the tensorflow version) on BitBucket and cloned the repo to work on it. Later I found that the original code was no longer available so I created this backup repo for my own convenience. This is why you can see some dirty changes in some files.
I guess you need to contact the authors for the information you need. 
Sorry that I cannot help you.

**Comment by ackdav** [comment]
oh, thank you very much for your explanation, now it makes sense. It wasn't clear to me that you weren't an author of the paper.
